// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck
export type FluentMessageId =
  | 'pref-apikey-label'
  | 'pref-apply-template'
  | 'pref-baseurl-label'
  | 'pref-fetch-models-btn'
  | 'pref-help'
  | 'pref-llm-section'
  | 'pref-model-label'
  | 'pref-prompt-section'
  | 'pref-provider-label'
  | 'pref-summarize-prompt-sublabel'
  | 'pref-system-prompt-sublabel'
  | 'pref-template-label'
  | 'pref-test-btn'
  | 'pref-test-connecting'
  | 'pref-test-fail'
  | 'pref-test-ok'
  | 'pref-title'
  | 'prefs-title'
  | 'reader-panel-head-text'
  | 'reader-panel-sidenav-tooltip'
  | 'startup-begin'
  | 'startup-finish';
