// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck

// prettier-ignore
declare namespace _ZoteroTypes {
  interface Prefs {
    PluginPrefsMap: {
      "llm.provider": string;
      "llm.openai.apiKey": string;
      "llm.openai.model": string;
      "llm.deepseek.apiKey": string;
      "llm.deepseek.model": string;
      "llm.anthropic.apiKey": string;
      "llm.anthropic.model": string;
      "llm.gemini.apiKey": string;
      "llm.gemini.model": string;
      "llm.ollama.baseUrl": string;
      "llm.ollama.model": string;
      "llm.temperature": string;
      "llm.maxTokens": string;
      "systemPrompt.content": string;
      "systemPrompt.userTemplates": string;
    };
  }
}
